spring.application.name=hospital management system


spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=krishna123
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
